// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

type Sender_Expecter struct {
	mock *mock.Mock
}

func (_m *Sender) EXPECT() *Sender_Expecter {
	return &Sender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type Sender
func (_mock *Sender) Send(ctx context.Context, to string, subject string, body string) error {
	ret := _mock.Called(ctx, to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Sender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Sender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - body string
func (_e *Sender_Expecter) Send(ctx interface{}, to interface{}, subject interface{}, body interface{}) *Sender_Send_Call {
	return &Sender_Send_Call{Call: _e.mock.On("Send", ctx, to, subject, body)}
}

func (_c *Sender_Send_Call) Run(run func(ctx context.Context, to string, subject string, body string)) *Sender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Sender_Send_Call) Return(err error) *Sender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Sender_Send_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, body string) error) *Sender_Send_Call {
	_c.Call.Return(run)
	return _c
}
