// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"hexagonal/internal/model"
	"hexagonal/internal/repository/reward"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AggregateForCustomer provides a mock function for the type Repository
func (_mock *Repository) AggregateForCustomer(ctx context.Context, customerID uuid.UUID) (reward.Aggregate, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for AggregateForCustomer")
	}

	var r0 reward.Aggregate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (reward.Aggregate, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) reward.Aggregate); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Get(0).(reward.Aggregate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_AggregateForCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateForCustomer'
type Repository_AggregateForCustomer_Call struct {
	*mock.Call
}

// AggregateForCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *Repository_Expecter) AggregateForCustomer(ctx interface{}, customerID interface{}) *Repository_AggregateForCustomer_Call {
	return &Repository_AggregateForCustomer_Call{Call: _e.mock.On("AggregateForCustomer", ctx, customerID)}
}

func (_c *Repository_AggregateForCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *Repository_AggregateForCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_AggregateForCustomer_Call) Return(aggregate reward.Aggregate, err error) *Repository_AggregateForCustomer_Call {
	_c.Call.Return(aggregate, err)
	return _c
}

func (_c *Repository_AggregateForCustomer_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) (reward.Aggregate, error)) *Repository_AggregateForCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomer provides a mock function for the type Repository
func (_mock *Repository) ListByCustomer(ctx context.Context, customerID uuid.UUID) ([]model.Reward, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomer")
	}

	var r0 []model.Reward
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Reward, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Reward); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Reward)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomer'
type Repository_ListByCustomer_Call struct {
	*mock.Call
}

// ListByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *Repository_Expecter) ListByCustomer(ctx interface{}, customerID interface{}) *Repository_ListByCustomer_Call {
	return &Repository_ListByCustomer_Call{Call: _e.mock.On("ListByCustomer", ctx, customerID)}
}

func (_c *Repository_ListByCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *Repository_ListByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListByCustomer_Call) Return(rewards []model.Reward, err error) *Repository_ListByCustomer_Call {
	_c.Call.Return(rewards, err)
	return _c
}

func (_c *Repository_ListByCustomer_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) ([]model.Reward, error)) *Repository_ListByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Repository
func (_mock *Repository) Save(ctx context.Context, rw *model.Reward) error {
	ret := _mock.Called(ctx, rw)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Reward) error); ok {
		r0 = returnFunc(ctx, rw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - rw *model.Reward
func (_e *Repository_Expecter) Save(ctx interface{}, rw interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, rw)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, rw *model.Reward)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Reward
		if args[1] != nil {
			arg1 = args[1].(*model.Reward)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Save_Call) Return(err error) *Repository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(ctx context.Context, rw *model.Reward) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}
