// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"hexagonal-modular-sidecar/internal/purchase/model"
	"hexagonal-modular-sidecar/internal/purchase/repository"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AggregateForCustomer provides a mock function for the type Repository
func (_mock *Repository) AggregateForCustomer(ctx context.Context, customerID uuid.UUID) (repository.Aggregate, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for AggregateForCustomer")
	}

	var r0 repository.Aggregate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Aggregate, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Aggregate); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Get(0).(repository.Aggregate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_AggregateForCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateForCustomer'
type Repository_AggregateForCustomer_Call struct {
	*mock.Call
}

// AggregateForCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *Repository_Expecter) AggregateForCustomer(ctx interface{}, customerID interface{}) *Repository_AggregateForCustomer_Call {
	return &Repository_AggregateForCustomer_Call{Call: _e.mock.On("AggregateForCustomer", ctx, customerID)}
}

func (_c *Repository_AggregateForCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *Repository_AggregateForCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_AggregateForCustomer_Call) Return(aggregate repository.Aggregate, err error) *Repository_AggregateForCustomer_Call {
	_c.Call.Return(aggregate, err)
	return _c
}

func (_c *Repository_AggregateForCustomer_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) (repository.Aggregate, error)) *Repository_AggregateForCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalPaymentID provides a mock function for the type Repository
func (_mock *Repository) FindByExternalPaymentID(ctx context.Context, externalID string) (model.Purchase, error) {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalPaymentID")
	}

	var r0 model.Purchase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Purchase, error)); ok {
		return returnFunc(ctx, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Purchase); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		r0 = ret.Get(0).(model.Purchase)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByExternalPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalPaymentID'
type Repository_FindByExternalPaymentID_Call struct {
	*mock.Call
}

// FindByExternalPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *Repository_Expecter) FindByExternalPaymentID(ctx interface{}, externalID interface{}) *Repository_FindByExternalPaymentID_Call {
	return &Repository_FindByExternalPaymentID_Call{Call: _e.mock.On("FindByExternalPaymentID", ctx, externalID)}
}

func (_c *Repository_FindByExternalPaymentID_Call) Run(run func(ctx context.Context, externalID string)) *Repository_FindByExternalPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByExternalPaymentID_Call) Return(purchase model.Purchase, err error) *Repository_FindByExternalPaymentID_Call {
	_c.Call.Return(purchase, err)
	return _c
}

func (_c *Repository_FindByExternalPaymentID_Call) RunAndReturn(run func(ctx context.Context, externalID string) (model.Purchase, error)) *Repository_FindByExternalPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type Repository
func (_mock *Repository) FindByID(ctx context.Context, id uuid.UUID) (model.Purchase, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.Purchase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Purchase, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Purchase); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Purchase)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(purchase model.Purchase, err error) *Repository_FindByID_Call {
	_c.Call.Return(purchase, err)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Purchase, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomer provides a mock function for the type Repository
func (_mock *Repository) ListByCustomer(ctx context.Context, customerID uuid.UUID) ([]model.Purchase, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomer")
	}

	var r0 []model.Purchase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Purchase, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Purchase); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Purchase)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomer'
type Repository_ListByCustomer_Call struct {
	*mock.Call
}

// ListByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *Repository_Expecter) ListByCustomer(ctx interface{}, customerID interface{}) *Repository_ListByCustomer_Call {
	return &Repository_ListByCustomer_Call{Call: _e.mock.On("ListByCustomer", ctx, customerID)}
}

func (_c *Repository_ListByCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *Repository_ListByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListByCustomer_Call) Return(purchases []model.Purchase, err error) *Repository_ListByCustomer_Call {
	_c.Call.Return(purchases, err)
	return _c
}

func (_c *Repository_ListByCustomer_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) ([]model.Purchase, error)) *Repository_ListByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefunded provides a mock function for the type Repository
func (_mock *Repository) MarkRefunded(ctx context.Context, id uuid.UUID, refundedAt time.Time) error {
	ret := _mock.Called(ctx, id, refundedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefunded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, refundedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_MarkRefunded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefunded'
type Repository_MarkRefunded_Call struct {
	*mock.Call
}

// MarkRefunded is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - refundedAt time.Time
func (_e *Repository_Expecter) MarkRefunded(ctx interface{}, id interface{}, refundedAt interface{}) *Repository_MarkRefunded_Call {
	return &Repository_MarkRefunded_Call{Call: _e.mock.On("MarkRefunded", ctx, id, refundedAt)}
}

func (_c *Repository_MarkRefunded_Call) Run(run func(ctx context.Context, id uuid.UUID, refundedAt time.Time)) *Repository_MarkRefunded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_MarkRefunded_Call) Return(err error) *Repository_MarkRefunded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_MarkRefunded_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, refundedAt time.Time) error) *Repository_MarkRefunded_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Repository
func (_mock *Repository) Save(ctx context.Context, p *model.Purchase) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Purchase) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - p *model.Purchase
func (_e *Repository_Expecter) Save(ctx interface{}, p interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, p)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, p *model.Purchase)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Purchase
		if args[1] != nil {
			arg1 = args[1].(*model.Purchase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Save_Call) Return(err error) *Repository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(ctx context.Context, p *model.Purchase) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}
