// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"hexagonal/internal/model"
	"hexagonal/internal/repository/customer"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ExistsByID provides a mock function for the type Repository
func (_mock *Repository) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type Repository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) ExistsByID(ctx interface{}, id interface{}) *Repository_ExistsByID_Call {
	return &Repository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *Repository_ExistsByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ExistsByID_Call) Return(b bool, err error) *Repository_ExistsByID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Repository_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *Repository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type Repository
func (_mock *Repository) FindByEmail(ctx context.Context, email string) (model.Customer, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Customer, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Customer); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(model.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type Repository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Repository_Expecter) FindByEmail(ctx interface{}, email interface{}) *Repository_FindByEmail_Call {
	return &Repository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *Repository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *Repository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByEmail_Call) Return(customer model.Customer, err error) *Repository_FindByEmail_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *Repository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (model.Customer, error)) *Repository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type Repository
func (_mock *Repository) FindByID(ctx context.Context, id uuid.UUID) (model.Customer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Customer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Customer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(customer model.Customer, err error) *Repository_FindByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Customer, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(ctx context.Context, f customer.ListFilter) ([]model.Customer, int64, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Customer
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, customer.ListFilter) ([]model.Customer, int64, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, customer.ListFilter) []model.Customer); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, customer.ListFilter) int64); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, customer.ListFilter) error); ok {
		r2 = returnFunc(ctx, f)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f customer.ListFilter
func (_e *Repository_Expecter) List(ctx interface{}, f interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, f customer.ListFilter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 customer.ListFilter
		if args[1] != nil {
			arg1 = args[1].(customer.ListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(customers []model.Customer, n int64, err error) *Repository_List_Call {
	_c.Call.Return(customers, n, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(ctx context.Context, f customer.ListFilter) ([]model.Customer, int64, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Repository
func (_mock *Repository) Save(ctx context.Context, c *model.Customer) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - c *model.Customer
func (_e *Repository_Expecter) Save(ctx interface{}, c interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, c)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, c *model.Customer)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Customer
		if args[1] != nil {
			arg1 = args[1].(*model.Customer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Save_Call) Return(err error) *Repository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(ctx context.Context, c *model.Customer) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository) Update(ctx context.Context, id uuid.UUID, updates map[string]any) (model.Customer, error) {
	ret := _mock.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (model.Customer, error)); ok {
		return returnFunc(ctx, id, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) model.Customer); ok {
		r0 = returnFunc(ctx, id, updates)
	} else {
		r0 = ret.Get(0).(model.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, id, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - updates map[string]any
func (_e *Repository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, updates map[string]any)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_Update_Call) Return(customer1 model.Customer, err error) *Repository_Update_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, updates map[string]any) (model.Customer, error)) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePoints provides a mock function for the type Repository
func (_mock *Repository) UpdatePoints(ctx context.Context, id uuid.UUID, points int) error {
	ret := _mock.Called(ctx, id, points)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePoints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, id, points)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_UpdatePoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePoints'
type Repository_UpdatePoints_Call struct {
	*mock.Call
}

// UpdatePoints is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - points int
func (_e *Repository_Expecter) UpdatePoints(ctx interface{}, id interface{}, points interface{}) *Repository_UpdatePoints_Call {
	return &Repository_UpdatePoints_Call{Call: _e.mock.On("UpdatePoints", ctx, id, points)}
}

func (_c *Repository_UpdatePoints_Call) Run(run func(ctx context.Context, id uuid.UUID, points int)) *Repository_UpdatePoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_UpdatePoints_Call) Return(err error) *Repository_UpdatePoints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_UpdatePoints_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, points int) error) *Repository_UpdatePoints_Call {
	_c.Call.Return(run)
	return _c
}
